# Site Settings
theme: bulma-clean-theme
lang: en
title: J0hnn1e20's Warehouse
tagline: 
email: J0hnn1e20@proton.me
description: >
  Meu blog e portifólio pessoal.
baseurl: ""
url: "https://johntelle.github.io/"
permalink: pretty
#favicon: /path/to/favicon.png
gh_sponsor: 
#hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr
force_theme: dark

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: J0hnn1e20


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass
  # load_paths: 
    # - node_modules

#google_analytics: UA-code-here
cookie_policy: /cookie-policy/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "J0hnn1e20"
      layout: post
      image: https://picsum.photos/id/16/800/600
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://picsum.photos/id/16/800/600
    show_sidebar: false

social:

  discord: https://discord.gg/
  youtube: https://www.youtube.com/@J0hnn1e20
  